"""Selected coded fields reviewed in build 25548639; values come from each capture.

Missing declarations become exceptions, never silent numeric fallbacks. Ammo address
joins require these reviewed loading helpers to retain their normalized syntax.
"""

EXPECTED_FIELDS = (('Creature', 'My_Ragdoll_Hum', '/hitInterval'),
 ('Creature', 'Player_Input', '/_CharFaction'),
 ('Creature', 'Zombie_Input', '/_CharFaction'),
 ('Creature', 'CMF.Mover', '/sensorType'),
 ('Hand_Tools', 'Scope_Info_Sets', '/scopeType'),
 ('Hand_Tools', 'Weapon_Melee', '/_DamageType'),
 ('Hand_Tools', 'Weapon_Melee', '/_repairType'),
 ('Hand_Tools', 'Weapon_Melee', '/_BladeDirect'),
 ('Hand_Tools', 'Weapon_Range', '/_DamageType'),
 ('Hand_Tools', 'Weapon_Range', '/_repairType'),
 ('Hand_Tools', 'Weapon_Range', '/_AmmoType'),
 ('Hand_Tools', 'Weapon_Range', '/_GunType'),
 ('Build_System', 'Build_Info', '/_Ground_Debris_Type'),
 ('Build_System', 'Build_Info', '/_ItemType'),
 ('Build_System', 'Build_Info', '/_Type'),
 ('Build_System', 'Build_Info', '/_interactType'),
 ('Build_System', 'Build_Info', '/_Collectable_Info/_CollectType'),
 ('UI', 'Craft_Items', '/_workbenchType'),
 ('UI', 'Special_Workbench', '/_workbenchType'),
 ('AI', 'Zombie_Agent', '/_moveType'),
 ('Equipment', 'Equipment_Info', '/_EquipBoneType'),
 ('UI', 'Slot_Info', '/_SlotType'),
 ('CompassPro', 'CompassNavigatorPro.CompassProPOI', '/visibility'),
 ('CompassPro', 'CompassNavigatorPro.CompassProPOI', '/titleVisibility'),
 ('CompassPro', 'CompassNavigatorPro.CompassProPOI', '/miniMapVisibility'),
 ('Creature', 'Skill_Mgr', '/_GrowthType'),
 ('Trap', 'Trap_RotBlade', '/_RotAxis'),
 ('Build_System', 'Top_Info', '/_Type'),
 ('Weather', 'Weather_Settings', '/weatherType'),
 ('Item_Info', 'Icon_Info', '/_SlotType'),
 ('Use_F', 'Object_Interact', '/_ContainerType'))

AMMO_RULE = ({'sha256': 'dc0cf3c743b19350a54cc28dbad05cf4b5e2357e29750af24362c6e0af3171cd',
  'symbol': {'kind': 'method',
             'member': 'Get_Ammo_IconRef',
             'parameters': ['Icon_Info', 'int'],
             'type': 'Item_Slot_Mgr'}},
 {'sha256': '3a4b3d9ed1ce4c4863975292b5a49a71b99f065595e14afaa68a5ac083471cfe',
  'symbol': {'kind': 'method',
             'member': 'Build_Ammo_Address',
             'parameters': ['string', 'int'],
             'type': 'Item_Slot_Mgr'}},
 {'sha256': '39595291cb31f0b315a34aea7ab687f74baa10f24cdf74489d3a79d06c5effeb',
  'symbol': {'kind': 'method',
             'member': 'Build_Caliber_Token_Candidates',
             'parameters': ['string', 'List<string>'],
             'type': 'Item_Slot_Mgr'}},
 {'sha256': 'caec72f59936cba48abd0372fe5475b4f48ebdc9f9ccf09321749549665dcda3',
  'symbol': {'kind': 'method',
             'member': 'Trim_Suffix',
             'parameters': ['string', 'string'],
             'type': 'Item_Slot_Mgr'}},
 {'sha256': 'bce083556978ea7a165edd632d121e3353f1e2f6e1cf801e8fcc048274786708',
  'symbol': {'kind': 'method',
             'member': 'Trim_Leading_Dot',
             'parameters': ['string'],
             'type': 'Item_Slot_Mgr'}},
 {'sha256': 'bbb2858c839d4323aecc32ca61693401ac35a1ce70d2a3a2fe885929c1aa3bc0',
  'symbol': {'kind': 'field', 'member': '_BulletMat_AddressNames', 'type': 'Item_Slot_Mgr'}})
